<?php ob_start(); ?>
<?php session_start(); if (isset($_SESSION['login']) && !empty($_SESSION['login'])): ?>
  <!-- Vérification des identifiants -->
      <p>Welcome <?= $_SESSION['login'] ?>.</p>
      <a href="?clear=logout" class="btn btn-danger">Disconnect</a>
<?php else: ?>
    <p>Wrongs identifier</p>
    <?php header("Location: index.php"); ?>
<?php endif ?>

<?php 
if(isset($_GET['clear']) && $_GET['clear'] === 'logout' ) {
    require_once './ressources/logout.php'; //Destruction de session pour bloquer l'acces par URL copié et forcer au login
    
}
 ?>
<?php $home = ob_get_clean(); ?>